// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3A91eJTvwDE4w8hn_KA21nxi-CMZNozo',
    appId: '1:28371618511:web:17458ce8f3b41066bf05ba',
    messagingSenderId: '28371618511',
    projectId: 'bookstore-eproject',
    authDomain: 'bookstore-eproject.firebaseapp.com',
    storageBucket: 'bookstore-eproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2YLJq6qwEVXQZmF9qYNMMfgzOA893rs',
    appId: '1:28371618511:android:37414c7b6a2d7de1bf05ba',
    messagingSenderId: '28371618511',
    projectId: 'bookstore-eproject',
    storageBucket: 'bookstore-eproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3osAzqNb3kIcNmdGJN_WQOEEKpw1N550',
    appId: '1:28371618511:ios:a26719a3e1427e44bf05ba',
    messagingSenderId: '28371618511',
    projectId: 'bookstore-eproject',
    storageBucket: 'bookstore-eproject.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3osAzqNb3kIcNmdGJN_WQOEEKpw1N550',
    appId: '1:28371618511:ios:a26719a3e1427e44bf05ba',
    messagingSenderId: '28371618511',
    projectId: 'bookstore-eproject',
    storageBucket: 'bookstore-eproject.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3A91eJTvwDE4w8hn_KA21nxi-CMZNozo',
    appId: '1:28371618511:web:411d0d9f15efd5c9bf05ba',
    messagingSenderId: '28371618511',
    projectId: 'bookstore-eproject',
    authDomain: 'bookstore-eproject.firebaseapp.com',
    storageBucket: 'bookstore-eproject.firebasestorage.app',
  );
}
